### ISSUE TITLE
Method User Client & Server (UserBothSideMethods.js)

### ISSUE THREAD

**Issue by J3m5** [HUB-HUmanBeing/HUmanBeing#26]
Si la méthode est appelée coté client, elle sera exécuter coté client et serveur. 
Il n'est pas nécessaire d'étendre la classe User dans le dossier lib.
Il suffit de déclarer les méthodes concernées directement dans la classe.
["Executing method from the client will call it in both client and server"](http://jagi.github.io/meteor-astronomy/#meteor-methods--220)

**Comment by robinBanquo** [comment]
je crois me souvenir que sans faire l'extend ca marchais pas, il me semble que c'etait lié au fait que du coup il retrouvais pas cette méthode coté serveur (puisque ce qui est dans import n'est coté serveur que si on le demande)... tu m'expliquera lundi comment on pourrais faire mieux si je me trompe
